sudo: required
services:
  - docker

before_install:
  - docker build -t antrancs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  antrancs/react-test npm test -- --coverage

after_success:
  - docker build -t antrancs/multi-client ./client
  - docker build -t antrancs/multi-nginx ./nginx
  - docker build -t antrancs/multi-server ./server
  - docker build -t antrancs/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push antrancs/multi-client
  - docker push antrancs/multi-nginx
  - docker push antrancs/multi-server
  - docker push antrancs/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-366918854453'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
